### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by BorisGautier** [rxcod9/joy-voyager-api#13]

**Comment by rxcod9** [comment]
Swagger documented filters may not be working

try sending data similar as datatable request format, it must work

**Comment by SouhailBS** [comment]
> Swagger documented filters may not be working
> 
> try sending data similar as datatable request format, it must work

can you provide us with an example?

**Comment by rxcod9** [comment]
> > Swagger documented filters may not be working
> > try sending data similar as datatable request format, it must work
> 
> can you provide us with an example?

This is not implemented yet
PRs are welcome :)

**Comment by rxcod9** [comment]
Update: Filter by text DataRow fields is working now

https://joy-voyager-api.herokuapp.com/api/documentation
