### ISSUE TITLE
language params

### ISSUE THREAD

**Issue by ruwad-co** [rxcod9/joy-voyager-api#14]
can you add language params to api 
like
https://joy-voyager-api.herokuapp.com/api/posts/1?lang=en

**Comment by rxcod9** [comment]
You can set app locale through middleware
Where you can receive language through query, header, body, or sub domain etc

**Comment by ruwad-co** [comment]
@rxcod9 
i have add changelanguage middleware and add to karnel


`<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\Request;

class ChangeLanguage
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle(Request $request, Closure $next)
    {
        app()->setLocale('ar');
        if(isset($request -> lang) && $request -> lang == 'en')
        app()->setLocale('en');
        return $next($request);
    }
}`

karnel
`       
 'changelang' => \App\Http\Middleware\ChangeLanguage::class,
`
where can add changelang Middleware now
sory i am new on laravel

**Comment by rxcod9** [comment]
@gogo207 

This should solve your problem 
https://stackoverflow.com/questions/38039159/how-to-assign-middleware-to-routes-in-laravel-better-way/50926301

**Comment by ruwad-co** [comment]
@rxcod9 
not working
The response is always returned in the default language and the response does not appear in the other language
`http://adensoft-voyager.com/api/articals/1?lang=en`

> {
    "data": {
        "id": 1,
        "title": "Title ar",
        "long_text": "Long Text ar",
        "created_at": "2021-11-05T10:27:00.000000Z",
        "updated_at": "2021-11-05T10:27:00.000000Z",
        "translations": [
            {
                "id": 45,
                "table_name": "articals",
                "column_name": "long_text",
                "foreign_key": 1,
                "locale": "en",
                "value": "Long Text en",
                "created_at": "2021-11-05T10:27:00.000000Z",
                "updated_at": "2021-11-05T10:27:00.000000Z"
            },
            {
                "id": 44,
                "table_name": "articals",
                "column_name": "title",
                "foreign_key": 1,
                "locale": "en",
                "value": "Title en",
                "created_at": "2021-11-05T10:27:00.000000Z",
                "updated_at": "2021-11-05T10:27:00.000000Z"
            }
        ]
    },
    "isModelTranslatable": true,
    "isSoftDeleted": false
}
