### ISSUE TITLE
resources folder are missing

### ISSUE THREAD

**Issue by lamualfa** [rxcod9/joy-voyager-api#15]
I have follow the installation instruction. But I get the error below when running the publish command:

I can't find the `resources` directory in `vendor/joy/voyager-api`.

https://github.com/rxcod9/joy-voyager-api/blob/3cee50bfc615180df13c3d8552b0ae39244044b3/src/VoyagerApiServiceProvider.php#L91

![image](https://user-images.githubusercontent.com/39755201/152822286-d599b5fb-fb0b-4a80-bef0-b1ef159aaf87.png)

<hr/>

My app directory:

![image](https://user-images.githubusercontent.com/39755201/152823177-606427d1-2514-48be-827f-6d15c21556a6.png)

**Comment by rxcod9** [comment]
Nice catch 

This is not blocking the setup though
Feel free to open a PR

**Comment by lamualfa** [comment]
@rxcod9 so I only have to add `resources/views` & `resources/lang` directory into `joy-voyager-api/src`? do those folders contain any specific files or just empty folders?

**Comment by rxcod9** [comment]
@lamualfa you can’t commit empty directories
You’ll have to add .gitkeep file inside those folders

**Comment by rxcod9** [comment]
Resolved
