### ISSUE TITLE
auth guard [api] is not defined

### ISSUE THREAD

**Issue by lamualfa** [rxcod9/joy-voyager-api#16]
# spesification

- php 8.0.8
- laravel 8.7.5

<hr/>

# step to reproduce

you can clone this repo [lamualfa/joy-voyager-api-issue](https://github.com/lamualfa/joy-voyager-api-issue) or follow the steps below from the scratch:

**create laravel template**

```bash
composer create-project laravel/laravel joy-voyager-api-issue
```

**navigate to project folder**

```bash
cd joy-voyager-api-issue
```

**install vendor**

```bash
composer install
```

**generate laravel key**

```bash
php artisan key:generate
```

**install voyager**

```bash
composer require joy/voyager-api
```

**install voyager dummy data**

```bash
php artisan voyager:install --with-dummy
```

**install joy-voyager-api**

```bash
composer require joy/voyager-api
```

**publish provider**

```bash
php artisan vendor:publish --provider="Joy\VoyagerApi\VoyagerApiServiceProvider" --force
```

**generate api documentation**

```bash
php artisan joy-voyager-api:l5-swagger:generate
```

**run the laravel server**

```bash
php artisan serve
```

**access the api**

`http://localhost:8000/api/menus`

and you'll get the error below:

![image](https://user-images.githubusercontent.com/39755201/152925064-9f0ca616-f635-41a9-a046-c14304914431.png)

**Comment by rxcod9** [comment]
Your “install voyager” step is wrong

As joy voyager-api-auth is added in dependency, you’ll need to setup passport as well

**Comment by lamualfa** [comment]
@rxcod9 thanks.
